# Generated by Django 4.0.1 on 2022-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=40)),
                ('notes', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
