# Generated by Django 4.0.1 on 2022-01-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lane'),
        ),
    ]
