# Generated by Django 4.0.1 on 2022-01-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_rename_tasks_task_lane_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='lane',
            name='user_id',
            field=models.ForeignKey(default='pat', on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='user_id'),
            preserve_default=False,
        ),
    ]
